################### CONFIGURATION  ################

logs:
  path: bins/log/logging.yaml #  full path to log yaml configuration file <relative to app>
  save_path: logs/ # log folder <relative to app> where to save log files


cache:
  enabled: true   # if cache is disabled, any cahce files are removed from the specified folder
  save_path: "data/cache"

sources:
  api_keys:    # needed to scrape transactions
    etherscan: ""     # etherscan API key
    polygonscan: ""   # polygonscan API key
    
  web3Providers:
    ethereum: ""  # web3 provider full url "https://...."
    polygon: ""
    optimism: ""
    arbitrum: ""
    celo: ""



